default: &default
  adapter: postgresql
  encoding: unicode
  username: 'postgres'
  password: '123'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: autumn_backend_development

test:
  <<: *default
  database: autumn_backend_test

production:
  <<: *default
  database: autumn_backend_production
  username: autumn_backend
  password: <%= ENV['AUTUMN_BACKEND_DATABASE_PASSWORD'] %>